
let rows = {id: 1,
  name_of_group: 'Family',
  contacts_id: 1,
  groups_id: 1,
  name: 'Fickry Bil Iman',
  company: 'Bil Corp',
  telp_number: '87819391999',
  email: 'fickry.bil.iman@gmail.com' }
  
console.log(rows.company);
// { id: 1,
//   name_of_group: 'Hacktiv8',
//   contacts_id: 1,
//   groups_id: 2,
//   name: 'Fickry Bil Iman',
//   company: 'Bil Corp',
//   telp_number: '87819391999',
//   email: 'fickry.bil.iman@gmail.com' },
// { id: 1,
//   name_of_group: 'Project',
//   contacts_id: 1,
//   groups_id: 3,
//   name: 'Fickry Bil Iman',
//   company: 'Bil Corp',
//   telp_number: '87819391999',
//   email: 'fickry.bil.iman@gmail.com' },
// { id: 2,
//   name_of_group: 'Project',
//   contacts_id: 2,
//   groups_id: 3,
//   name: 'Kokoh',
//   company: 'Kokoh Corp',
//   telp_number: '5325623623',
//   email: 'kokoh@kokoh.com' },
// { id: 1,
//   name_of_group: 'SDN 24',
//   contacts_id: 1,
//   groups_id: 4,
//   name: 'Fickry Bil Iman',
//   company: 'Bil Corp',
//   telp_number: '87819391999',
//   email: 'fickry.bil.iman@gmail.com' }